# Base image with study.wrangler and all dependencies
FROM rocker/tidyverse:4

## system dependencies for building some R packages
RUN apt-get update && apt-get install -y \
	libglpk-dev \
	libxml2-dev

COPY . /study.wrangler
WORKDIR /study.wrangler

### CRAN dependencies
RUN R -e "install.packages('skimr')"

### GitHub dependencies (order matters!)
# plot.data dependencies not automatically installed:
RUN R -e "install.packages('BiocManager')"
RUN R -e "BiocManager::install('SummarizedExperiment')"
RUN R -e "BiocManager::install('DESeq2')"
RUN R -e "remotes::install_github('VEuPathDB/veupathUtils', 'v2.7.0', upgrade_dependencies=F)"

# plot.data for binwidth function
RUN R -e "remotes::install_github('VEuPathDB/plot.data', 'v5.4.2', upgrade_dependencies=F)"

### Install study.wrangler locally
RUN R -e "install.packages('/study.wrangler', repos=NULL, type='source')"

# Verify installation
RUN R -e "library(study.wrangler); cat('study.wrangler loaded successfully\n')"